##### CRIA TABELA NO BANCO #####
CREATE DATABASE mycontacts;

##### ABILITANDO O UUID NO POSTGRES #####
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

##### CRIA TABELA DE CATEGORIAS #####
CREATE TABLE IF NOT EXISTS categories(
id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
name VARCHAR NOT NULL
);

##### CRIA TABELA DE CONTACTS #####
CREATE TABLE IF NOT EXISTS contacts(
id UUID NOT NULL UNIQUE DEFAULT uuid_generate_v4(),
name VARCHAR NOT NULL,
email VARCHAR UNIQUE,
phone VARCHAR,
category_id UUID,
FOREIGN KEY (category_id) REFERENCES categories(id)
);

